version: "3.7"

services:
  postgres-pmr:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5432:5432/tcp"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_PASSWORD=shop
      - PGUSER=postgres
      - PGPASSWORD=shop

volumes:
  pg-data:
